### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by Achie72** [Achie72/clock_mage#4]
A better update could be used for much better presentation.
See example in [Neon Runner](https://github.com/Achie72/neon-runner)

Image could be grabbed from the [itch.io](https://achie.itch.io/clock-mage) site with:

`![alt text](link)` format

---

Moreover this update could contain blogs related to this project.

https://achie.itch.io/clock-mage/devlog/300012/updates-and-future-plans
https://ko-fi.com/post/NdabJam-results-MyLittleRogueLikeJam1-Twitter-S-I3I01Q6AG
https://dev.to/achie72/hacktoberfest-2021-pr-1-30dm

**Comment by kisbg** [comment]
Hi Achie72 ! I created a pull request based on the issue :)
 #6
